### ISSUE TITLE
同步問題-車子會被特殊引力吸到一起

### ISSUE THREAD

**Issue by zhian66** [ChengHung-Wang/boom-car#11]
左邊畫面的 playerIndex = 0, 右邊為 1
<img width="1440" alt="image" src="https://github.com/ChengHung-Wang/boom-car/assets/50503333/212c18bc-5153-4541-b6f0-b876db773254">

跑到後面兩台車的位置會變得很奇怪，然後就會出現 1 或 0 被同步到另一台車的身上。
<img width="1440" alt="image" src="https://github.com/ChengHung-Wang/boom-car/assets/50503333/d1566ebc-5c33-44ae-a657-626d517db611">

如上圖，先看右邊小地圖，明明 1 與 0 的實際位置差了很多，但左邊的小地圖顯示兩台車卻是連在一起的。

**Comment by nalivvo** [comment]
兩台車的位置剛開始的直線都沒什麼問題
但進到第一個彎道之後
index 0的小地圖移動的距離
明顯比index 1的小地圖移動距離大很多

左邊是index 0右邊是index 1
彎道的部分不知道有什麼問題
<img width="275" alt="Screenshot 2023-06-14 at 21 13 00" src="https://github.com/ChengHung-Wang/boom-car/assets/113707231/f1d3e2be-da98-4830-926c-912aa6473b3b">
<img width="281" alt="Screenshot 2023-06-14 at 21 13 10" src="https://github.com/ChengHung-Wang/boom-car/assets/113707231/dc1ce0e3-97d8-4882-ba10-1e3898616196">

**Comment by zhian66** [comment]
解決了哈哈哈哈
7433944a6358d6c5d8b896a908b23d32a5b8fb60
